overblog_graphql:
    definitions:
        schema:
            user:
                query: UserQuery
                mutation: UserMutation
            library:
                query: LibraryQuery
                mutation: LibraryMutation
        mappings:
            types:
                -
                    type: graphql
                    dir: "%kernel.project_dir%/config/graphql"
                    suffix: null
