networks:
  network:
    name: ${COMPOSE_PROJECT_NAME}_${NETWORK_NAME}
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET_IP}

services:
  nginx:
    image: ${COMPOSE_PROJECT_NAME}_nginx
    build:
      context: nginx
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    working_dir: /var/www/html
    networks:
      - network
    volumes:
      - ../:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/templates-available:/etc/nginx/templates-available
      - ./nginx/ssl/:/etc/nginx/ssl
    ports:
      - 80:80
      - 443:443

  php-fpm:
    image: ${COMPOSE_PROJECT_NAME}_php-fpm
    build:
      context: php-fpm
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    container_name: ${COMPOSE_PROJECT_NAME}_php-fpm
    working_dir: /var/www/html
    networks:
      - network
    volumes:
      - ../:/var/www/html
      - ./php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - ./nginx/ssl/:/usr/local/share/ca-certificates
      - ./php-fpm/home/:/home/appuser
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
      XDEBUG_MODE: "debug"
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=${XDEBUG_CLIENT_PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    image: mysql:8.0
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    networks:
      - network
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - ${PORT_MYSQL}:3306

  mail:
    image: mailhog/mailhog
    container_name: ${COMPOSE_PROJECT_NAME}_mail
    networks:
      - network
    ports:
      - ${PORT_MAIL_SMTP}:1025 # email test server
      - ${PORT_MAIL_GUI}:8025 # email test server

volumes:
  mysql-data:
